server:
  port: 8443

spring:
  datasource:
    url: jdbc:mysql://cdb-ezjh4cma.bj.tencentcdb.com:10210/Baike?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abcd1234
    driverClassName: com.mysql.cj.jdbc.Driver
  http:
    multipart:
      max-file-size: 2GB
      max-request-size: 5GB

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.baike.model
  config-location: classpath:mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true

